.pragma library

// 気象庁 天気コード表（www.jma.go.jp の TELOPS より生成）
// tools/generate_data.py が書き出すので手で編集しない
// code -> [Breezeアイコン名, 日本語ラベル]
var TELOPS = {
    "100": ["weather-clear", "晴"],
    "101": ["weather-few-clouds", "晴時々曇"],
    "102": ["weather-showers-scattered-day", "晴一時雨"],
    "103": ["weather-showers-scattered-day", "晴時々雨"],
    "104": ["weather-snow-scattered-day", "晴一時雪"],
    "105": ["weather-snow-scattered-day", "晴時々雪"],
    "106": ["weather-showers-scattered-day", "晴一時雨か雪"],
    "107": ["weather-showers-scattered-day", "晴時々雨か雪"],
    "108": ["weather-showers-scattered-day", "晴一時雨か雷雨"],
    "110": ["weather-few-clouds", "晴後時々曇"],
    "111": ["weather-few-clouds", "晴後曇"],
    "112": ["weather-showers-scattered-day", "晴後一時雨"],
    "113": ["weather-showers-scattered-day", "晴後時々雨"],
    "114": ["weather-showers-scattered-day", "晴後雨"],
    "115": ["weather-snow-scattered-day", "晴後一時雪"],
    "116": ["weather-snow-scattered-day", "晴後時々雪"],
    "117": ["weather-snow-scattered-day", "晴後雪"],
    "118": ["weather-showers-scattered-day", "晴後雨か雪"],
    "119": ["weather-showers-scattered-day", "晴後雨か雷雨"],
    "120": ["weather-showers-scattered-day", "晴朝夕一時雨"],
    "121": ["weather-showers-scattered-day", "晴朝の内一時雨"],
    "122": ["weather-showers-scattered-day", "晴夕方一時雨"],
    "123": ["weather-clear", "晴山沿い雷雨"],
    "124": ["weather-clear", "晴山沿い雪"],
    "125": ["weather-showers-scattered-day", "晴午後は雷雨"],
    "126": ["weather-showers-scattered-day", "晴昼頃から雨"],
    "127": ["weather-showers-scattered-day", "晴夕方から雨"],
    "128": ["weather-showers-scattered-day", "晴夜は雨"],
    "130": ["weather-clear", "朝の内霧後晴"],
    "131": ["weather-clear", "晴明け方霧"],
    "132": ["weather-few-clouds", "晴朝夕曇"],
    "140": ["weather-showers-scattered-day", "晴時々雨で雷を伴う"],
    "160": ["weather-snow-scattered-day", "晴一時雪か雨"],
    "170": ["weather-snow-scattered-day", "晴時々雪か雨"],
    "181": ["weather-snow-scattered-day", "晴後雪か雨"],
    "200": ["weather-many-clouds", "曇"],
    "201": ["weather-clouds", "曇時々晴"],
    "202": ["weather-showers-scattered", "曇一時雨"],
    "203": ["weather-showers-scattered", "曇時々雨"],
    "204": ["weather-snow-scattered", "曇一時雪"],
    "205": ["weather-snow-scattered", "曇時々雪"],
    "206": ["weather-showers-scattered", "曇一時雨か雪"],
    "207": ["weather-showers-scattered", "曇時々雨か雪"],
    "208": ["weather-showers-scattered", "曇一時雨か雷雨"],
    "209": ["weather-many-clouds", "霧"],
    "210": ["weather-clouds", "曇後時々晴"],
    "211": ["weather-clouds", "曇後晴"],
    "212": ["weather-showers-scattered", "曇後一時雨"],
    "213": ["weather-showers-scattered", "曇後時々雨"],
    "214": ["weather-showers-scattered", "曇後雨"],
    "215": ["weather-snow-scattered", "曇後一時雪"],
    "216": ["weather-snow-scattered", "曇後時々雪"],
    "217": ["weather-snow-scattered", "曇後雪"],
    "218": ["weather-showers-scattered", "曇後雨か雪"],
    "219": ["weather-showers-scattered", "曇後雨か雷雨"],
    "220": ["weather-showers-scattered", "曇朝夕一時雨"],
    "221": ["weather-showers-scattered", "曇朝の内一時雨"],
    "222": ["weather-showers-scattered", "曇夕方一時雨"],
    "223": ["weather-clouds", "曇日中時々晴"],
    "224": ["weather-showers-scattered", "曇昼頃から雨"],
    "225": ["weather-showers-scattered", "曇夕方から雨"],
    "226": ["weather-showers-scattered", "曇夜は雨"],
    "228": ["weather-snow-scattered", "曇昼頃から雪"],
    "229": ["weather-snow-scattered", "曇夕方から雪"],
    "230": ["weather-snow-scattered", "曇夜は雪"],
    "231": ["weather-many-clouds", "曇海上海岸は霧か霧雨"],
    "240": ["weather-showers-scattered", "曇時々雨で雷を伴う"],
    "250": ["weather-snow-scattered", "曇時々雪で雷を伴う"],
    "260": ["weather-snow-scattered", "曇一時雪か雨"],
    "270": ["weather-snow-scattered", "曇時々雪か雨"],
    "281": ["weather-snow-scattered", "曇後雪か雨"],
    "300": ["weather-showers", "雨"],
    "301": ["weather-showers-day", "雨時々晴"],
    "302": ["weather-showers-scattered", "雨時々止む"],
    "303": ["weather-snow-rain", "雨時々雪"],
    "304": ["weather-showers", "雨か雪"],
    "306": ["weather-showers", "大雨"],
    "308": ["weather-storm", "雨で暴風を伴う"],
    "309": ["weather-snow-rain", "雨一時雪"],
    "311": ["weather-showers-day", "雨後晴"],
    "313": ["weather-showers", "雨後曇"],
    "314": ["weather-snow-rain", "雨後時々雪"],
    "315": ["weather-snow-rain", "雨後雪"],
    "316": ["weather-showers-day", "雨か雪後晴"],
    "317": ["weather-showers", "雨か雪後曇"],
    "320": ["weather-showers-day", "朝の内雨後晴"],
    "321": ["weather-showers", "朝の内雨後曇"],
    "322": ["weather-snow-rain", "雨朝晩一時雪"],
    "323": ["weather-showers-day", "雨昼頃から晴"],
    "324": ["weather-showers-day", "雨夕方から晴"],
    "325": ["weather-showers-day", "雨夜は晴"],
    "326": ["weather-snow-rain", "雨夕方から雪"],
    "327": ["weather-snow-rain", "雨夜は雪"],
    "328": ["weather-showers", "雨一時強く降る"],
    "329": ["weather-showers", "雨一時みぞれ"],
    "340": ["weather-snow", "雪か雨"],
    "350": ["weather-showers", "雨で雷を伴う"],
    "361": ["weather-snow-scattered-day", "雪か雨後晴"],
    "371": ["weather-snow-scattered", "雪か雨後曇"],
    "400": ["weather-snow", "雪"],
    "401": ["weather-snow-scattered-day", "雪時々晴"],
    "402": ["weather-snow-scattered", "雪時々止む"],
    "403": ["weather-snow-rain", "雪時々雨"],
    "405": ["weather-snow", "大雪"],
    "406": ["weather-snow-storm", "風雪強い"],
    "407": ["weather-snow-storm", "暴風雪"],
    "409": ["weather-snow-rain", "雪一時雨"],
    "411": ["weather-snow-scattered-day", "雪後晴"],
    "413": ["weather-snow-scattered", "雪後曇"],
    "414": ["weather-snow-rain", "雪後雨"],
    "420": ["weather-snow-scattered-day", "朝の内雪後晴"],
    "421": ["weather-snow-scattered", "朝の内雪後曇"],
    "422": ["weather-snow-rain", "雪昼頃から雨"],
    "423": ["weather-snow-rain", "雪夕方から雨"],
    "425": ["weather-snow", "雪一時強く降る"],
    "426": ["weather-snow", "雪後みぞれ"],
    "427": ["weather-snow", "雪一時みぞれ"],
    "450": ["weather-snow", "雪で雷を伴う"]
};

var NIGHT = {
    "weather-clear": "weather-clear-night",
    "weather-few-clouds": "weather-few-clouds-night",
    "weather-clouds": "weather-clouds-night",
    "weather-showers-day": "weather-showers-night",
    "weather-showers-scattered-day": "weather-showers-scattered-night",
    "weather-snow-scattered-day": "weather-snow-scattered-night"
};

function icon(code, night) {
    var e = TELOPS[String(code)];
    if (!e) return "weather-none-available";
    return night && NIGHT[e[0]] ? NIGHT[e[0]] : e[0];
}

function label(code) {
    var e = TELOPS[String(code)];
    return e ? e[1] : "--";
}
